---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- name: client
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: clients-51588606-6052-4296-badb-0d5582b32acf
      file: 
      path: 
  label: Client
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY-MM-DD
    time_format: ''
    export_format: YYYY-MM-DD
    display_utc: true
  default: now
  hidden: true
- type: tag_list
  name: categories
  label: Categories
- type: color
  name: project_bg_color
  config:
    color_format: Hex
  label: Background color
- type: color
  name: project_fg_color
  config:
    color_format: Hex
  label: Foreground color
- name: featured
  type: boolean
  label: Featured
pages:
- projects/3d-graff.md
- projects/chelsea-landmark.md
- projects/ios-concept.md
- projects/sunk.md
